name: CI

on: [pull_request]

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.1.0

  macOS:
    runs-on: macOS-latest
    env:
      XCODE_VERSION: ${{ '13.1' }}
    steps:
      - name: Install docker
        run: |
          brew install docker-machine docker
          sudo docker --version
      - name: Select Xcode
        run: "sudo xcode-select -s /Applications/Xcode_$XCODE_VERSION.app"
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Run
        run: rake build[release]
      - name: Test
        run: rake test
      - name: E2ETests
        run: rake e2e_only
